#!/bin/bash

TARGET_FILE=$1
MODELS_DIRECTORY=$2
MODEL_FILE_NAME_PATTERN=$3
OUTPUT_DIRECTORY=$4

for MODEL_FILE in `find $MODELS_DIRECTORY -name "$MODEL_FILE_NAME_PATTERN" -type f`
do
  echo "Processing $MODEL_FILE"
  ./cad_score.bash $TARGET_FILE $MODEL_FILE $OUTPUT_DIRECTORY
done
