#!/bin/bash

OUTPUT_DIRECTORY=$1
TARGETS_DIRECTORY=$2
TARGET_FILE_NAME_PATTERN=$3
MODELS_DIRECTORY=$4
MODEL_FILE_NAME_PATTERN=$5
FILTERS_DIRECTORY=$6
FILTER_FILE_NAME_PATTERN=$7

for TARGET_FILE in `find $TARGETS_DIRECTORY -name "$TARGET_FILE_NAME_PATTERN" -type f`
do
  for MODEL_FILE in `find $MODELS_DIRECTORY -name "$MODEL_FILE_NAME_PATTERN" -type f`
  do
    echo "Scoring $TARGET_FILE $MODEL_FILE"
    ./cad_score.bash $OUTPUT_DIRECTORY $TARGET_FILE $MODEL_FILE
    for FILTER_FILE in `find $FILTERS_DIRECTORY -name "$FILTER_FILE_NAME_PATTERN" -type f`
    do
      echo "Using filter $FILTER_FILE"
      ./cad_score.bash $OUTPUT_DIRECTORY $TARGET_FILE $MODEL_FILE $FILTER_FILE
    done
  done
done
