#!/bin/bash

SCRIPT_FILE=$1
TARGET_FILE=$2
MODELS_DIRECTORY=$3
MODEL_FILE_NAME_PATTERN=$4
OUTPUT_DIRECTORY=$5

for MODEL_FILE in `find $MODELS_DIRECTORY -name "$MODEL_FILE_NAME_PATTERN" -type f`
do
  echo "Processing $MODEL_FILE"
  bash $SCRIPT_FILE $TARGET_FILE $MODEL_FILE $OUTPUT_DIRECTORY
done
