#!/bin/bash

SCRIPT_FILE=$1
TARGETS_DIRECTORY=$2
TARGET_FILE_NAME_PATTERN=$3
MODELS_DIRECTORY=$4
MODEL_FILE_NAME_PATTERN=$5
OUTPUT_DIRECTORY=$6

for TARGET_FILE in `find $TARGETS_DIRECTORY -name "$TARGET_FILE_NAME_PATTERN" -type f`
do
  for MODEL_FILE in `find $MODELS_DIRECTORY -name "$MODEL_FILE_NAME_PATTERN" -type f`
  do
    echo "Scoring $TARGET_FILE $MODEL_FILE"
    bash $SCRIPT_FILE $TARGET_FILE $MODEL_FILE $OUTPUT_DIRECTORY
  done
done
